name: contactrate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24
  - scipy=1.10
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - arviz
  - pymc
  - jupyterlab
  - scikit-learn
  - pip